FROM node:10.6
#FROM node:10.6-alpine TODO: use a slim

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN npm install
RUN npm install -g @angular/cli@1.7.1

CMD [ "node" ]